// The Cloudflare entry: the Next.js app that OpenNext builds, plus the Durable Object classes it stores sessions in.
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`, so it only type-checks after one.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { default as handler } from "../.open-next/worker.js";

export { LimiterObject, SessionObject } from "./session-object";

export default {
  fetch: handler.fetch,
} satisfies ExportedHandler<CloudflareEnv>;
